extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern Vtx castle_grounds_dl_Main_mesh_vtx_0[18];
extern Gfx castle_grounds_dl_Main_mesh_tri_0[];
extern Vtx castle_grounds_dl_Main_mesh_vtx_1[60];
extern Gfx castle_grounds_dl_Main_mesh_tri_1[];
extern Vtx castle_grounds_dl_Main_mesh_vtx_2[94];
extern Gfx castle_grounds_dl_Main_mesh_tri_2[];
extern Vtx castle_grounds_dl_Main_mesh_vtx_3[683];
extern Gfx castle_grounds_dl_Main_mesh_tri_3[];
extern Vtx castle_grounds_dl_Main_mesh_vtx_4[8];
extern Gfx castle_grounds_dl_Main_mesh_tri_4[];
extern Vtx castle_grounds_dl_Main_mesh_vtx_5[70];
extern Gfx castle_grounds_dl_Main_mesh_tri_5[];
extern Vtx castle_grounds_dl_Main_mesh_vtx_6[48];
extern Gfx castle_grounds_dl_Main_mesh_tri_6[];
extern Vtx castle_grounds_dl_Main_mesh_vtx_7[56];
extern Gfx castle_grounds_dl_Main_mesh_tri_7[];
extern Vtx castle_grounds_dl_Main_mesh_vtx_8[8];
extern Gfx castle_grounds_dl_Main_mesh_tri_8[];
extern Vtx castle_grounds_dl_Main_mesh_vtx_9[208];
extern Gfx castle_grounds_dl_Main_mesh_tri_9[];
extern Vtx castle_grounds_dl_Main_mesh_vtx_10[38];
extern Gfx castle_grounds_dl_Main_mesh_tri_10[];
extern Vtx castle_grounds_dl_Main_001_mesh_vtx_0[54];
extern Gfx castle_grounds_dl_Main_001_mesh_tri_0[];
extern Vtx castle_grounds_dl_Nonsolid_mesh_vtx_0[27];
extern Gfx castle_grounds_dl_Nonsolid_mesh_tri_0[];
extern Vtx castle_grounds_dl_Nonsolid_mesh_vtx_1[4];
extern Gfx castle_grounds_dl_Nonsolid_mesh_tri_1[];
extern Vtx castle_grounds_dl_Nonsolid_mesh_vtx_2[4];
extern Gfx castle_grounds_dl_Nonsolid_mesh_tri_2[];
extern Vtx castle_grounds_dl_Nonsolid_mesh_vtx_3[61];
extern Gfx castle_grounds_dl_Nonsolid_mesh_tri_3[];
extern Vtx castle_grounds_dl_Nonsolid_mesh_vtx_4[4];
extern Gfx castle_grounds_dl_Nonsolid_mesh_tri_4[];
extern Vtx castle_grounds_dl_Nonsolid_mesh_vtx_5[4];
extern Gfx castle_grounds_dl_Nonsolid_mesh_tri_5[];
extern Vtx castle_grounds_dl_Nonsolid_mesh_vtx_6[4];
extern Gfx castle_grounds_dl_Nonsolid_mesh_tri_6[];
extern Vtx castle_grounds_dl_Nonsolid_mesh_vtx_7[4];
extern Gfx castle_grounds_dl_Nonsolid_mesh_tri_7[];
extern Vtx castle_grounds_dl_Nonsolid_mesh_vtx_8[4];
extern Gfx castle_grounds_dl_Nonsolid_mesh_tri_8[];
extern Vtx castle_grounds_dl_Nonsolid_mesh_vtx_9[4];
extern Gfx castle_grounds_dl_Nonsolid_mesh_tri_9[];
extern Vtx castle_grounds_dl_Nonsolid_mesh_vtx_10[4];
extern Gfx castle_grounds_dl_Nonsolid_mesh_tri_10[];
extern Vtx castle_grounds_dl_Nonsolid_mesh_vtx_11[4];
extern Gfx castle_grounds_dl_Nonsolid_mesh_tri_11[];
extern Vtx castle_grounds_dl_Nonsolid_mesh_vtx_12[4];
extern Gfx castle_grounds_dl_Nonsolid_mesh_tri_12[];

extern Gfx castle_grounds_dl_Main_mesh[];
extern Gfx castle_grounds_dl_Main_001_mesh[];
extern Gfx castle_grounds_dl_Nonsolid_mesh[];
extern Gfx castle_grounds_dl_material_revert_render_settings[];

